In [2]:
import autograd.numpy as np
from autograd import grad, elementwise_grad

In [5]:
g = lambda x, w: 5 * x + 7 * w
dgdx = elementwise_grad(g, 0)

dgdx(1.0, 1.0)

5.0

In [6]:
g(2, 1)

17

In [7]:
f = lambda w, x: 3 * x + 6 * w + g(x, w)
f(2, 1)

34

In [8]:
dfdx = elementwise_grad(f, 1)

In [9]:
dfdx(1.0, 1.0)

8.0

In [7]:
h = lambda x: np.array([3 * x**2, 4 * x])

dhdx = elementwise_grad(h, 0)

dhdx(np.array([1, 2, 3]))

array([10., 16., 22.])

In [12]:
t = np.arange(0, 1, 0.01)
t.shape

(100,)

In [13]:
t = t.reshape(-1, t.size)
t.shape

(1, 100)

In [24]:
class something:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def f(self, x, y):
        return x**2 + y**2

    def derivative(self):
        return grad(self.f, 0)(self.x, self.y)

In [25]:
a = something(2.0, 3.0)

a.derivative()

4.0

In [4]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

np.append(a, b, axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.append(np.array([[None] * 3]), b, axis=0)

array([[array(None, dtype=object), array(None, dtype=object),
        array(None, dtype=object)],
       [4, 5, 6]], dtype=object)

In [14]:
c = []

c.append(a)
c.append(b)
np.array(c)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [19]:
a.reshape(a.size)

array([1, 2, 3])

In [23]:
class A:
    def __init__(self, x):
        self.x = x


a = A(1)

a.x += 1
a.x

2

In [25]:
b = [A(1), A(2), A(3)]
b.x

AttributeError: 'list' object has no attribute 'x'

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b

array([ 4, 10, 18])

In [29]:
print("\033[91m", a)

 [1 2 3]


In [30]:
def fn(x, y):
    if x > 0:
        return x**2 + 3 * y**2
    else:
        return 3 * x**2 + y**2

In [33]:
grad(fn, 1)(1.0, 2.0)

12.0

In [4]:
A = ["dick", "cock", "balls"]
for i, a in enumerate(A):
    print(i, a)
    a = "hello world"

print(A)

0 dick
1 cock
2 balls
['dick', 'cock', 'balls']
